### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by matthewmcgarvey**

### CODE REVIEW

**Review by av-pinzur — CHANGES_REQUESTED** [review]
One person doesn't seem sufficient. @matthewmcgarvey / @rickpeyton, do you know of other Ruby devs at Ramsey who would like to share this responsibility? Or better yet, a leader who could commit a team to it?

**Comment by matthewmcgarvey** [comment]
@av-pinzur feel free to update who owns the repo but can this go through so I stop getting updates and john sloan is taken off?

**Comment by rickpeyton** [comment]
@matthewmcgarvey I tried to push to your branch, but the update is not showing. It is probably related to Github issues.

Can you update to 

```yaml
# https://help.github.com/articles/about-codeowners/

# https://github.com/orgs/RamseyInHouse/teams/ruby
*   @RamseyInHouse/ruby
```

I added @av-pinzur and @aaricpittman ruby team. I was the only member of the team.

We can't apply our normal team dynamics to this since there is just a small subset of our team members in this org.

**Comment by matthewmcgarvey** [comment]
@rickpeyton @av-pinzur It's updated now

**Review by av-pinzur — APPROVED** [review]

**Review by rickpeyton — APPROVED** [review]

**Pull request merged**
