### PR TITLE
Add templates for pull requests and issues

### PR DESCRIPTION
**Pull request by jasjar72**
Adding these to round out the [community profile checklist](https://github.com/RamseyInHouse/ramsey-cop/community).

### CODE REVIEW

**Comment by jwsloan** [comment]
I agree. We should take this as a pattern for all of our OSS offerings. @jasjar72 did you come up with these ones on your own?

**Comment by jasjar72** [comment]
@jwsloan I adapted them from a host of examples I found online.

**Comment by rickpeyton** [comment]
But I see what @jasjar72 added is a little more robust. I like it.

**Comment by jwsloan** [comment]
I like it!

**Pull request merged**
